# Generated by Django 4.2 on 2023-04-29 02:41

import Library_Management_System.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('surname', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to=Library_Management_System.utils.PathAndRename('authors/'))),
            ],
        ),
        migrations.CreateModel(
            name='BorrowerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('how_many_books_can_be_borrowed', models.IntegerField()),
                ('late_payment_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=Library_Management_System.utils.PathAndRename('borrowers/'))),
                ('birthdate', models.DateField()),
                ('user_created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('borrower_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='borrowers', to='user.borrowertype')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
