# Generated by Django 4.2 on 2023-04-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='library_books_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
