# Generated by Django 4.2 on 2023-04-29 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowertype',
            name='weeks_for_return',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
