# Generated by Django 4.2 on 2023-04-29 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_borrowertype_weeks_for_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowertype',
            name='borrowed_books',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
