# Generated by Django 4.2 on 2023-04-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_borrowertype_borrowed_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowertype',
            name='borrowed_books',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
