# Generated by Django 4.2 on 2023-04-26 00:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_author_issued_books_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='user_created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
