# Generated by Django 4.2 on 2023-04-29 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_borrowertype_borrowed_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowertype',
            name='borrowed_books',
        ),
        migrations.AddField(
            model_name='borrower',
            name='borrowed_books',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
